adb shell pm uninstall --user 0 com.linkedin.android
adb shell pm uninstall --user 0 com.mcprohosting.beam
adb shell pm uninstall --user 0 com.mcprohosting.beam.beta
adb shell pm uninstall --user 0 com.microsoft.ageofempirescastlesiege
adb shell pm uninstall --user 0 com.microsoft.amp.apps.bingfinance
adb shell pm uninstall --user 0 com.microsoft.amp.apps.bingnews
adb shell pm uninstall --user 0 com.microsoft.amp.apps.bingsports
adb shell pm uninstall --user 0 com.microsoft.amp.apps.bingweather
adb shell pm uninstall --user 0 com.microsoft.android.bingplaces
adb shell pm uninstall --user 0 com.microsoft.android.smsorganizer
adb shell pm uninstall --user 0 com.microsoft.appmanager
adb shell pm uninstall --user 0 com.microsoft.azure
adb shell pm uninstall --user 0 com.microsoft.beambroadcast
adb shell pm uninstall --user 0 com.microsoft.bing
adb shell pm uninstall --user 0 com.microsoft.bing.wallpapers
adb shell pm uninstall --user 0 com.microsoft.bingads
adb shell pm uninstall --user 0 com.microsoft.bingrewards
adb shell pm uninstall --user 0 com.microsoft.cortana
adb shell pm uninstall --user 0 com.microsoft.cortana.preview
adb shell pm uninstall --user 0 com.microsoft.crm.crmhost
adb shell pm uninstall --user 0 com.microsoft.crm.crmphone
adb shell pm uninstall --user 0 com.microsoft.crm.crmphone.fieldServices
adb shell pm uninstall --user 0 com.microsoft.crm.crmphone.sales
adb shell pm uninstall --user 0 com.microsoft.crm.crmtablet
adb shell pm uninstall --user 0 com.microsoft.d365.fs.mobile
adb shell pm uninstall --user 0 com.microsoft.delvemobile
adb shell pm uninstall --user 0 com.microsoft.device.samples.dualscreenexperience
adb shell pm uninstall --user 0 com.microsoft.dynamics.nav
adb shell pm uninstall --user 0 com.microsoft.dynamics.ProjectMadeira
adb shell pm uninstall --user 0 com.microsoft.dynamics365.operations.mobile
adb shell pm uninstall --user 0 com.microsoft.emmx
adb shell pm uninstall --user 0 com.microsoft.emmx.beta
adb shell pm uninstall --user 0 com.microsoft.emmx.canary
adb shell pm uninstall --user 0 com.microsoft.emmx.dev
adb shell pm uninstall --user 0 com.microsoft.exchange.bookings
adb shell pm uninstall --user 0 com.microsoft.exchange.mowa
adb shell pm uninstall --user 0 com.microsoft.faceswap
adb shell pm uninstall --user 0 com.microsoft.familysafety
adb shell pm uninstall --user 0 com.microsoft.flow
adb shell pm uninstall --user 0 com.microsoft.fuselabs.dlife
adb shell pm uninstall --user 0 com.microsoft.garage.sketch360app
adb shell pm uninstall --user 0 com.microsoft.gearspop
adb shell pm uninstall --user 0 com.microsoft.gravity
adb shell pm uninstall --user 0 com.microsoft.halochannel
adb shell pm uninstall --user 0 com.microsoft.hockeyapp.testerapp
adb shell pm uninstall --user 0 com.microsoft.hub_keyboard
adb shell pm uninstall --user 0 com.microsoft.hyperlapsemobile
adb shell pm uninstall --user 0 com.microsoft.intune
adb shell pm uninstall --user 0 com.microsoft.intune.mam.managedbrowser
adb shell pm uninstall --user 0 com.microsoft.ipviewer
adb shell pm uninstall --user 0 com.microsoft.kapp
adb shell pm uninstall --user 0 com.microsoft.keyboardforexcel
adb shell pm uninstall --user 0 com.microsoft.launcher
adb shell pm uninstall --user 0 com.microsoft.launcher.enterprise
adb shell pm uninstall --user 0 com.microsoft.launcher.zan
adb shell pm uninstall --user 0 com.microsoft.lists.public
adb shell pm uninstall --user 0 com.microsoft.mahjong
adb shell pm uninstall --user 0 com.microsoft.math
adb shell pm uninstall --user 0 com.microsoft.microsoftdynamics365projecttimesheet
adb shell pm uninstall --user 0 com.microsoft.microsoftsolitairecollection
adb shell pm uninstall --user 0 com.microsoft.mimickeralarm
adb shell pm uninstall --user 0 com.microsoft.mobile.polymer
adb shell pm uninstall --user 0 com.microsoft.mobile.sprightly
adb shell pm uninstall --user 0 com.microsoft.msapps
adb shell pm uninstall --user 0 com.microsoft.msra.followus.app
adb shell pm uninstall --user 0 com.microsoft.next
adb shell pm uninstall --user 0 com.microsoft.office.excel
adb shell pm uninstall --user 0 com.microsoft.office.lync
adb shell pm uninstall --user 0 com.microsoft.office.lync15
adb shell pm uninstall --user 0 com.microsoft.office.officehub
adb shell pm uninstall --user 0 com.microsoft.office.officehubrow
adb shell pm uninstall --user 0 com.microsoft.office.officelens
adb shell pm uninstall --user 0 com.microsoft.office.onenote
adb shell pm uninstall --user 0 com.microsoft.office.outlook
adb shell pm uninstall --user 0 com.microsoft.office.powerpoint
adb shell pm uninstall --user 0 com.microsoft.office.word
adb shell pm uninstall --user 0 com.microsoft.outlookgroups
adb shell pm uninstall --user 0 com.microsoft.outlooklite
adb shell pm uninstall --user 0 com.microsoft.PhotosCompanion
adb shell pm uninstall --user 0 com.microsoft.planner
adb shell pm uninstall --user 0 com.microsoft.powerbim
adb shell pm uninstall --user 0 com.microsoft.ramobile
adb shell pm uninstall --user 0 com.microsoft.rdc.android
adb shell pm uninstall --user 0 com.microsoft.rdc.android.beta
adb shell pm uninstall --user 0 com.microsoft.rdc.androidx
adb shell pm uninstall --user 0 com.microsoft.research.cmt
adb shell pm uninstall --user 0 com.microsoft.scmx
adb shell pm uninstall --user 0 com.microsoft.sharepoint
adb shell pm uninstall --user 0 com.microsoft.skydrive
adb shell pm uninstall --user 0 com.microsoft.smartglass
adb shell pm uninstall --user 0 com.microsoft.stream
adb shell pm uninstall --user 0 com.microsoft.sudoku
adb shell pm uninstall --user 0 com.microsoft.surfaceaudio
adb shell pm uninstall --user 0 com.microsoft.teams
adb shell pm uninstall --user 0 com.microsoft.todos
adb shell pm uninstall --user 0 com.microsoft.translator
adb shell pm uninstall --user 0 com.Microsoft.WarehouseManagement
adb shell pm uninstall --user 0 com.microsoft.whiteboard.publicpreview
adb shell pm uninstall --user 0 com.microsoft.windowsintune.companyportal
adb shell pm uninstall --user 0 com.microsoft.wordament
adb shell pm uninstall --user 0 com.microsoft.workfolders
adb shell pm uninstall --user 0 com.microsoft.xboxfamily
adb shell pm uninstall --user 0 com.microsoft.xboxmusic
adb shell pm uninstall --user 0 com.microsoft.xboxone.smartglass
adb shell pm uninstall --user 0 com.microsoft.xboxone.smartglass.beta
adb shell pm uninstall --user 0 com.microsoft.xcloud
adb shell pm uninstall --user 0 com.microsoft.xle
adb shell pm uninstall --user 0 com.microsoftselfie
adb shell pm uninstall --user 0 com.ms.office365admin